/* tslint:disable */
/* eslint-disable */
/**
 * Rosetta
 * Build Once. Integrate Your Blockchain Everywhere.
 *
 * The version of the OpenAPI document: 1.4.10
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists } from '../runtime';
import {
    AccountIdentifier,
    AccountIdentifierFromJSON,
    AccountIdentifierToJSON,
    Currency,
    CurrencyFromJSON,
    CurrencyToJSON,
    NetworkIdentifier,
    NetworkIdentifierFromJSON,
    NetworkIdentifierToJSON,
    PartialBlockIdentifier,
    PartialBlockIdentifierFromJSON,
    PartialBlockIdentifierToJSON,
} from './';

/**
 * An AccountBalanceRequest is utilized to make a balance request on the /account/balance endpoint. If the block_identifier is populated, a historical balance query should be performed.
 * @export
 * @interface AccountBalanceRequest
 */
export interface AccountBalanceRequest {
    /**
     *
     * @type {NetworkIdentifier}
     * @memberof AccountBalanceRequest
     */
    network_identifier: NetworkIdentifier;
    /**
     *
     * @type {AccountIdentifier}
     * @memberof AccountBalanceRequest
     */
    account_identifier: AccountIdentifier;
    /**
     *
     * @type {PartialBlockIdentifier}
     * @memberof AccountBalanceRequest
     */
    block_identifier?: PartialBlockIdentifier;
    /**
     * In some cases, the caller may not want to retrieve all available balances for an AccountIdentifier. If the currencies field is populated, only balances for the specified currencies will be returned. If not populated, all available balances will be returned.
     * @type {Array<Currency>}
     * @memberof AccountBalanceRequest
     */
    currencies?: Array<Currency>;
}

export function AccountBalanceRequestFromJSON(json: any): AccountBalanceRequest {
    return AccountBalanceRequestFromJSONTyped(json, false);
}

export function AccountBalanceRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccountBalanceRequest {
    if (json === undefined || json === null) {
        return json;
    }
    return {
        network_identifier: NetworkIdentifierFromJSON(json['network_identifier']),
        account_identifier: AccountIdentifierFromJSON(json['account_identifier']),
        block_identifier: !exists(json, 'block_identifier') ? undefined : PartialBlockIdentifierFromJSON(json['block_identifier']),
        currencies: !exists(json, 'currencies') ? undefined : (json['currencies'] as Array<any>).map(CurrencyFromJSON),
    };
}

export function AccountBalanceRequestToJSON(value?: AccountBalanceRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        network_identifier: NetworkIdentifierToJSON(value.network_identifier),
        account_identifier: AccountIdentifierToJSON(value.account_identifier),
        block_identifier: PartialBlockIdentifierToJSON(value.block_identifier),
        currencies: value.currencies === undefined ? undefined : (value.currencies as Array<any>).map(CurrencyToJSON),
    };
}
