/* tslint:disable */
/* eslint-disable */
/**
 * Rosetta
 * Build Once. Integrate Your Blockchain Everywhere.
 *
 * The version of the OpenAPI document: 1.4.10
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists } from '../runtime';
import {
    BalanceExemption,
    BalanceExemptionFromJSON,
    BalanceExemptionToJSON,
    ModelError,
    ModelErrorFromJSON,
    ModelErrorToJSON,
    OperationStatus,
    OperationStatusFromJSON,
    OperationStatusToJSON,
} from './';

/**
 * Allow specifies supported Operation status, Operation types, and all possible error statuses. This Allow object is used by clients to validate the correctness of a Rosetta Server implementation. It is expected that these clients will error if they receive some response that contains any of the above information that is not specified here.
 * @export
 * @interface Allow
 */
export interface Allow {
    /**
     * All Operation.Status this implementation supports. Any status that is returned during parsing that is not listed here will cause client validation to error.
     * @type {Array<OperationStatus>}
     * @memberof Allow
     */
    operation_statuses: Array<OperationStatus>;
    /**
     * All Operation.Type this implementation supports. Any type that is returned during parsing that is not listed here will cause client validation to error.
     * @type {Array<string>}
     * @memberof Allow
     */
    operation_types: Array<string>;
    /**
     * All Errors that this implementation could return. Any error that is returned during parsing that is not listed here will cause client validation to error.
     * @type {Array<ModelError>}
     * @memberof Allow
     */
    errors: Array<ModelError>;
    /**
     * Any Rosetta implementation that supports querying the balance of an account at any height in the past should set this to true.
     * @type {boolean}
     * @memberof Allow
     */
    historical_balance_lookup: boolean;
    /**
     * If populated, `timestamp_start_index` indicates the first block index where block timestamps are considered valid (i.e. all blocks less than `timestamp_start_index` could have invalid timestamps). This is useful when the genesis block (or blocks) of a network have timestamp 0. If not populated, block timestamps are assumed to be valid for all available blocks.
     * @type {number}
     * @memberof Allow
     */
    timestamp_start_index?: number;
    /**
     * All methods that are supported by the /call endpoint. Communicating which parameters should be provided to /call is the responsibility of the implementer (this is en lieu of defining an entire type system and requiring the implementer to define that in Allow).
     * @type {Array<string>}
     * @memberof Allow
     */
    call_methods: Array<string>;
    /**
     * BalanceExemptions is an array of BalanceExemption indicating which account balances could change without a corresponding Operation. BalanceExemptions should be used sparingly as they may introduce significant complexity for integrators that attempt to reconcile all account balance changes. If your implementation relies on any BalanceExemptions, you MUST implement historical balance lookup (the ability to query an account balance at any BlockIdentifier).
     * @type {Array<BalanceExemption>}
     * @memberof Allow
     */
    balance_exemptions: Array<BalanceExemption>;
    /**
     * Any Rosetta implementation that can update an AccountIdentifier's unspent coins based on the contents of the mempool should populate this field as true. If false, requests to `/account/coins` that set `include_mempool` as true will be automatically rejected.
     * @type {boolean}
     * @memberof Allow
     */
    mempool_coins: boolean;
}

export function AllowFromJSON(json: any): Allow {
    return AllowFromJSONTyped(json, false);
}

export function AllowFromJSONTyped(json: any, ignoreDiscriminator: boolean): Allow {
    if (json === undefined || json === null) {
        return json;
    }
    return {
        operation_statuses: (json['operation_statuses'] as Array<any>).map(OperationStatusFromJSON),
        operation_types: json['operation_types'],
        errors: (json['errors'] as Array<any>).map(ModelErrorFromJSON),
        historical_balance_lookup: json['historical_balance_lookup'],
        timestamp_start_index: !exists(json, 'timestamp_start_index') ? undefined : json['timestamp_start_index'],
        call_methods: json['call_methods'],
        balance_exemptions: (json['balance_exemptions'] as Array<any>).map(BalanceExemptionFromJSON),
        mempool_coins: json['mempool_coins'],
    };
}

export function AllowToJSON(value?: Allow | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        operation_statuses: (value.operation_statuses as Array<any>).map(OperationStatusToJSON),
        operation_types: value.operation_types,
        errors: (value.errors as Array<any>).map(ModelErrorToJSON),
        historical_balance_lookup: value.historical_balance_lookup,
        timestamp_start_index: value.timestamp_start_index,
        call_methods: value.call_methods,
        balance_exemptions: (value.balance_exemptions as Array<any>).map(BalanceExemptionToJSON),
        mempool_coins: value.mempool_coins,
    };
}
