/* tslint:disable */
/* eslint-disable */
/**
 * Rosetta
 * Build Once. Integrate Your Blockchain Everywhere.
 *
 * The version of the OpenAPI document: 1.4.10
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    NetworkIdentifier,
    NetworkIdentifierFromJSON,
    NetworkIdentifierToJSON,
    PartialBlockIdentifier,
    PartialBlockIdentifierFromJSON,
    PartialBlockIdentifierToJSON,
} from './';

/**
 * A BlockRequest is utilized to make a block request on the /block endpoint.
 * @export
 * @interface BlockRequest
 */
export interface BlockRequest {
    /**
     *
     * @type {NetworkIdentifier}
     * @memberof BlockRequest
     */
    network_identifier: NetworkIdentifier;
    /**
     *
     * @type {PartialBlockIdentifier}
     * @memberof BlockRequest
     */
    block_identifier: PartialBlockIdentifier;
}

export function BlockRequestFromJSON(json: any): BlockRequest {
    return BlockRequestFromJSONTyped(json, false);
}

export function BlockRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): BlockRequest {
    if (json === undefined || json === null) {
        return json;
    }
    return {
        network_identifier: NetworkIdentifierFromJSON(json['network_identifier']),
        block_identifier: PartialBlockIdentifierFromJSON(json['block_identifier']),
    };
}

export function BlockRequestToJSON(value?: BlockRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        network_identifier: NetworkIdentifierToJSON(value.network_identifier),
        block_identifier: PartialBlockIdentifierToJSON(value.block_identifier),
    };
}
