/* tslint:disable */
/* eslint-disable */
/**
 * Rosetta
 * Build Once. Integrate Your Blockchain Everywhere.
 *
 * The version of the OpenAPI document: 1.4.10
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Transaction, TransactionFromJSON, TransactionToJSON } from './';

/**
 * A BlockTransactionResponse contains information about a block transaction.
 * @export
 * @interface BlockTransactionResponse
 */
export interface BlockTransactionResponse {
    /**
     *
     * @type {Transaction}
     * @memberof BlockTransactionResponse
     */
    transaction: Transaction;
}

export function BlockTransactionResponseFromJSON(json: any): BlockTransactionResponse {
    return BlockTransactionResponseFromJSONTyped(json, false);
}

export function BlockTransactionResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): BlockTransactionResponse {
    if (json === undefined || json === null) {
        return json;
    }
    return {
        transaction: TransactionFromJSON(json['transaction']),
    };
}

export function BlockTransactionResponseToJSON(value?: BlockTransactionResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        transaction: TransactionToJSON(value.transaction),
    };
}
