/* tslint:disable */
/* eslint-disable */
/**
 * Rosetta
 * Build Once. Integrate Your Blockchain Everywhere.
 *
 * The version of the OpenAPI document: 1.4.10
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists } from '../runtime';
import { Block, BlockFromJSON, BlockToJSON, TransactionIdentifier, TransactionIdentifierFromJSON, TransactionIdentifierToJSON } from './';

/**
 * A BlockResponse includes a fully-populated block or a partially-populated block with a list of other transactions to fetch (other_transactions). As a result of the consensus algorithm of some blockchains, blocks can be omitted (i.e. certain block indices can be skipped). If a query for one of these omitted indices is made, the response should not include a `Block` object. It is VERY important to note that blocks MUST still form a canonical, connected chain of blocks where each block has a unique index. In other words, the `PartialBlockIdentifier` of a block after an omitted block should reference the last non-omitted block.
 * @export
 * @interface BlockResponse
 */
export interface BlockResponse {
    /**
     *
     * @type {Block}
     * @memberof BlockResponse
     */
    block?: Block;
    /**
     * Some blockchains may require additional transactions to be fetched that weren't returned in the block response (ex: block only returns transaction hashes). For blockchains with a lot of transactions in each block, this can be very useful as consumers can concurrently fetch all transactions returned.
     * @type {Array<TransactionIdentifier>}
     * @memberof BlockResponse
     */
    other_transactions?: Array<TransactionIdentifier>;
}

export function BlockResponseFromJSON(json: any): BlockResponse {
    return BlockResponseFromJSONTyped(json, false);
}

export function BlockResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): BlockResponse {
    if (json === undefined || json === null) {
        return json;
    }
    return {
        block: !exists(json, 'block') ? undefined : BlockFromJSON(json['block']),
        other_transactions: !exists(json, 'other_transactions')
            ? undefined
            : (json['other_transactions'] as Array<any>).map(TransactionIdentifierFromJSON),
    };
}

export function BlockResponseToJSON(value?: BlockResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        block: BlockToJSON(value.block),
        other_transactions:
            value.other_transactions === undefined ? undefined : (value.other_transactions as Array<any>).map(TransactionIdentifierToJSON),
    };
}
