/* tslint:disable */
/* eslint-disable */
/**
 * Rosetta
 * Build Once. Integrate Your Blockchain Everywhere.
 *
 * The version of the OpenAPI document: 1.4.10
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * BlockEventType determines if a BlockEvent represents the addition or removal of a block.
 * @export
 * @enum {string}
 */
export enum BlockEventType {
    added = 'block_added',
    removed = 'block_removed',
}

export function BlockEventTypeFromJSON(json: any): BlockEventType {
    return BlockEventTypeFromJSONTyped(json, false);
}

export function BlockEventTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): BlockEventType {
    return json as BlockEventType;
}

export function BlockEventTypeToJSON(value?: BlockEventType | null): any {
    return value as any;
}
