/* tslint:disable */
/* eslint-disable */
/**
 * Rosetta
 * Build Once. Integrate Your Blockchain Everywhere.
 *
 * The version of the OpenAPI document: 1.4.10
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { BlockIdentifier, BlockIdentifierFromJSON, BlockIdentifierToJSON, Transaction, TransactionFromJSON, TransactionToJSON } from './';

/**
 * BlockTransaction contains a populated Transaction and the BlockIdentifier that contains it.
 * @export
 * @interface BlockTransaction
 */
export interface BlockTransaction {
    /**
     *
     * @type {BlockIdentifier}
     * @memberof BlockTransaction
     */
    block_identifier: BlockIdentifier;
    /**
     *
     * @type {Transaction}
     * @memberof BlockTransaction
     */
    transaction: Transaction;
}

export function BlockTransactionFromJSON(json: any): BlockTransaction {
    return BlockTransactionFromJSONTyped(json, false);
}

export function BlockTransactionFromJSONTyped(json: any, ignoreDiscriminator: boolean): BlockTransaction {
    if (json === undefined || json === null) {
        return json;
    }
    return {
        block_identifier: BlockIdentifierFromJSON(json['block_identifier']),
        transaction: TransactionFromJSON(json['transaction']),
    };
}

export function BlockTransactionToJSON(value?: BlockTransaction | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        block_identifier: BlockIdentifierToJSON(value.block_identifier),
        transaction: TransactionToJSON(value.transaction),
    };
}
