/* tslint:disable */
/* eslint-disable */
/**
 * Rosetta
 * Build Once. Integrate Your Blockchain Everywhere.
 *
 * The version of the OpenAPI document: 1.4.10
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Amount, AmountFromJSON, AmountToJSON, CoinIdentifier, CoinIdentifierFromJSON, CoinIdentifierToJSON } from './';

/**
 * Coin contains its unique identifier and the amount it represents.
 * @export
 * @interface Coin
 */
export interface Coin {
    /**
     *
     * @type {CoinIdentifier}
     * @memberof Coin
     */
    coin_identifier: CoinIdentifier;
    /**
     *
     * @type {Amount}
     * @memberof Coin
     */
    amount: Amount;
}

export function CoinFromJSON(json: any): Coin {
    return CoinFromJSONTyped(json, false);
}

export function CoinFromJSONTyped(json: any, ignoreDiscriminator: boolean): Coin {
    if (json === undefined || json === null) {
        return json;
    }
    return {
        coin_identifier: CoinIdentifierFromJSON(json['coin_identifier']),
        amount: AmountFromJSON(json['amount']),
    };
}

export function CoinToJSON(value?: Coin | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        coin_identifier: CoinIdentifierToJSON(value.coin_identifier),
        amount: AmountToJSON(value.amount),
    };
}
