/* tslint:disable */
/* eslint-disable */
/**
 * Rosetta
 * Build Once. Integrate Your Blockchain Everywhere.
 *
 * The version of the OpenAPI document: 1.4.10
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * CoinActions are different state changes that a Coin can undergo. When a Coin is created, it is coin_created. When a Coin is spent, it is coin_spent. It is assumed that a single Coin cannot be created or spent more than once.
 * @export
 * @enum {string}
 */
export enum CoinAction {
    created = 'coin_created',
    spent = 'coin_spent',
}

export function CoinActionFromJSON(json: any): CoinAction {
    return CoinActionFromJSONTyped(json, false);
}

export function CoinActionFromJSONTyped(json: any, ignoreDiscriminator: boolean): CoinAction {
    return json as CoinAction;
}

export function CoinActionToJSON(value?: CoinAction | null): any {
    return value as any;
}
