/* tslint:disable */
/* eslint-disable */
/**
 * Rosetta
 * Build Once. Integrate Your Blockchain Everywhere.
 *
 * The version of the OpenAPI document: 1.4.10
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CoinAction, CoinActionFromJSON, CoinActionToJSON, CoinIdentifier, CoinIdentifierFromJSON, CoinIdentifierToJSON } from './';

/**
 * CoinChange is used to represent a change in state of a some coin identified by a coin_identifier. This object is part of the Operation model and must be populated for UTXO-based blockchains. Coincidentally, this abstraction of UTXOs allows for supporting both account-based transfers and UTXO-based transfers on the same blockchain (when a transfer is account-based, don't populate this model).
 * @export
 * @interface CoinChange
 */
export interface CoinChange {
    /**
     *
     * @type {CoinIdentifier}
     * @memberof CoinChange
     */
    coin_identifier: CoinIdentifier;
    /**
     *
     * @type {CoinAction}
     * @memberof CoinChange
     */
    coin_action: CoinAction;
}

export function CoinChangeFromJSON(json: any): CoinChange {
    return CoinChangeFromJSONTyped(json, false);
}

export function CoinChangeFromJSONTyped(json: any, ignoreDiscriminator: boolean): CoinChange {
    if (json === undefined || json === null) {
        return json;
    }
    return {
        coin_identifier: CoinIdentifierFromJSON(json['coin_identifier']),
        coin_action: CoinActionFromJSON(json['coin_action']),
    };
}

export function CoinChangeToJSON(value?: CoinChange | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        coin_identifier: CoinIdentifierToJSON(value.coin_identifier),
        coin_action: CoinActionToJSON(value.coin_action),
    };
}
