/* tslint:disable */
/* eslint-disable */
/**
 * Rosetta
 * Build Once. Integrate Your Blockchain Everywhere.
 *
 * The version of the OpenAPI document: 1.4.10
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { NetworkIdentifier, NetworkIdentifierFromJSON, NetworkIdentifierToJSON } from './';

/**
 * The transaction submission request includes a signed transaction.
 * @export
 * @interface ConstructionSubmitRequest
 */
export interface ConstructionSubmitRequest {
    /**
     *
     * @type {NetworkIdentifier}
     * @memberof ConstructionSubmitRequest
     */
    network_identifier: NetworkIdentifier;
    /**
     *
     * @type {string}
     * @memberof ConstructionSubmitRequest
     */
    signed_transaction: string;
}

export function ConstructionSubmitRequestFromJSON(json: any): ConstructionSubmitRequest {
    return ConstructionSubmitRequestFromJSONTyped(json, false);
}

export function ConstructionSubmitRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConstructionSubmitRequest {
    if (json === undefined || json === null) {
        return json;
    }
    return {
        network_identifier: NetworkIdentifierFromJSON(json['network_identifier']),
        signed_transaction: json['signed_transaction'],
    };
}

export function ConstructionSubmitRequestToJSON(value?: ConstructionSubmitRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        network_identifier: NetworkIdentifierToJSON(value.network_identifier),
        signed_transaction: value.signed_transaction,
    };
}
