/* tslint:disable */
/* eslint-disable */
/**
 * Rosetta
 * Build Once. Integrate Your Blockchain Everywhere.
 *
 * The version of the OpenAPI document: 1.4.10
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists } from '../runtime';
import { AccountIdentifier, AccountIdentifierFromJSON, AccountIdentifierToJSON } from './';

/**
 * ConstructionPreprocessResponse contains `options` that will be sent unmodified to `/construction/metadata`. If it is not necessary to make a request to `/construction/metadata`, `options` should be omitted.  Some blockchains require the PublicKey of particular AccountIdentifiers to construct a valid transaction. To fetch these PublicKeys, populate `required_public_keys` with the AccountIdentifiers associated with the desired PublicKeys. If it is not necessary to retrieve any PublicKeys for construction, `required_public_keys` should be omitted.
 * @export
 * @interface ConstructionPreprocessResponse
 */
export interface ConstructionPreprocessResponse {
    /**
     * The options that will be sent directly to `/construction/metadata` by the caller.
     * @type {object}
     * @memberof ConstructionPreprocessResponse
     */
    options?: object;
    /**
     *
     * @type {Array<AccountIdentifier>}
     * @memberof ConstructionPreprocessResponse
     */
    required_public_keys?: Array<AccountIdentifier>;
}

export function ConstructionPreprocessResponseFromJSON(json: any): ConstructionPreprocessResponse {
    return ConstructionPreprocessResponseFromJSONTyped(json, false);
}

export function ConstructionPreprocessResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConstructionPreprocessResponse {
    if (json === undefined || json === null) {
        return json;
    }
    return {
        options: !exists(json, 'options') ? undefined : json['options'],
        required_public_keys: !exists(json, 'required_public_keys')
            ? undefined
            : (json['required_public_keys'] as Array<any>).map(AccountIdentifierFromJSON),
    };
}

export function ConstructionPreprocessResponseToJSON(value?: ConstructionPreprocessResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        options: value.options,
        required_public_keys:
            value.required_public_keys === undefined ? undefined : (value.required_public_keys as Array<any>).map(AccountIdentifierToJSON),
    };
}
