/* tslint:disable */
/* eslint-disable */
/**
 * Rosetta
 * Build Once. Integrate Your Blockchain Everywhere.
 *
 * The version of the OpenAPI document: 1.4.10
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { SigningPayload, SigningPayloadFromJSON, SigningPayloadToJSON } from './';

/**
 * ConstructionTransactionResponse is returned by `/construction/payloads`. It contains an unsigned transaction blob (that is usually needed to construct the a network transaction from a collection of signatures) and an array of payloads that must be signed by the caller.
 * @export
 * @interface ConstructionPayloadsResponse
 */
export interface ConstructionPayloadsResponse {
    /**
     *
     * @type {string}
     * @memberof ConstructionPayloadsResponse
     */
    unsigned_transaction: string;
    /**
     *
     * @type {Array<SigningPayload>}
     * @memberof ConstructionPayloadsResponse
     */
    payloads: Array<SigningPayload>;
}

export function ConstructionPayloadsResponseFromJSON(json: any): ConstructionPayloadsResponse {
    return ConstructionPayloadsResponseFromJSONTyped(json, false);
}

export function ConstructionPayloadsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConstructionPayloadsResponse {
    if (json === undefined || json === null) {
        return json;
    }
    return {
        unsigned_transaction: json['unsigned_transaction'],
        payloads: (json['payloads'] as Array<any>).map(SigningPayloadFromJSON),
    };
}

export function ConstructionPayloadsResponseToJSON(value?: ConstructionPayloadsResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        unsigned_transaction: value.unsigned_transaction,
        payloads: (value.payloads as Array<any>).map(SigningPayloadToJSON),
    };
}
