/* tslint:disable */
/* eslint-disable */
/**
 * Rosetta
 * Build Once. Integrate Your Blockchain Everywhere.
 *
 * The version of the OpenAPI document: 1.4.10
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Used by RelatedTransaction to indicate the direction of the relation (i.e. cross-shard/cross-network sends may reference `backward` to an earlier transaction and async execution may reference `forward`). Can be used to indicate if a transaction relation is from child to parent or the reverse.
 * @export
 * @enum {string}
 */
export enum Direction {
    forward = 'forward',
    backward = 'backward',
}

export function DirectionFromJSON(json: any): Direction {
    return DirectionFromJSONTyped(json, false);
}

export function DirectionFromJSONTyped(json: any, ignoreDiscriminator: boolean): Direction {
    return json as Direction;
}

export function DirectionToJSON(value?: Direction | null): any {
    return value as any;
}
