/* tslint:disable */
/* eslint-disable */
/**
 * Rosetta
 * Build Once. Integrate Your Blockchain Everywhere.
 *
 * The version of the OpenAPI document: 1.4.10
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * ExemptionType is used to indicate if the live balance for an account subject to a BalanceExemption could increase above, decrease below, or equal the computed balance. * greater_or_equal: The live balance may increase above or equal the computed balance. This typically   occurs with staking rewards that accrue on each block. * less_or_equal: The live balance may decrease below or equal the computed balance. This typically   occurs as balance moves from locked to spendable on a vesting account. * dynamic: The live balance may increase above, decrease below, or equal the computed balance. This   typically occurs with tokens that have a dynamic supply.
 * @export
 * @enum {string}
 */
export enum ExemptionType {
    greater_or_equal = 'greater_or_equal',
    less_or_equal = 'less_or_equal',
    dynamic = 'dynamic',
}

export function ExemptionTypeFromJSON(json: any): ExemptionType {
    return ExemptionTypeFromJSONTyped(json, false);
}

export function ExemptionTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExemptionType {
    return json as ExemptionType;
}

export function ExemptionTypeToJSON(value?: ExemptionType | null): any {
    return value as any;
}
