/* tslint:disable */
/* eslint-disable */
/**
 * Rosetta
 * Build Once. Integrate Your Blockchain Everywhere.
 *
 * The version of the OpenAPI document: 1.4.10
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    NetworkIdentifier,
    NetworkIdentifierFromJSON,
    NetworkIdentifierToJSON,
    TransactionIdentifier,
    TransactionIdentifierFromJSON,
    TransactionIdentifierToJSON,
} from './';

/**
 * A MempoolTransactionRequest is utilized to retrieve a transaction from the mempool.
 * @export
 * @interface MempoolTransactionRequest
 */
export interface MempoolTransactionRequest {
    /**
     *
     * @type {NetworkIdentifier}
     * @memberof MempoolTransactionRequest
     */
    network_identifier: NetworkIdentifier;
    /**
     *
     * @type {TransactionIdentifier}
     * @memberof MempoolTransactionRequest
     */
    transaction_identifier: TransactionIdentifier;
}

export function MempoolTransactionRequestFromJSON(json: any): MempoolTransactionRequest {
    return MempoolTransactionRequestFromJSONTyped(json, false);
}

export function MempoolTransactionRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): MempoolTransactionRequest {
    if (json === undefined || json === null) {
        return json;
    }
    return {
        network_identifier: NetworkIdentifierFromJSON(json['network_identifier']),
        transaction_identifier: TransactionIdentifierFromJSON(json['transaction_identifier']),
    };
}

export function MempoolTransactionRequestToJSON(value?: MempoolTransactionRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        network_identifier: NetworkIdentifierToJSON(value.network_identifier),
        transaction_identifier: TransactionIdentifierToJSON(value.transaction_identifier),
    };
}
