/* tslint:disable */
/* eslint-disable */
/**
 * Rosetta
 * Build Once. Integrate Your Blockchain Everywhere.
 *
 * The version of the OpenAPI document: 1.4.10
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { TransactionIdentifier, TransactionIdentifierFromJSON, TransactionIdentifierToJSON } from './';

/**
 * A MempoolResponse contains all transaction identifiers in the mempool for a particular network_identifier.
 * @export
 * @interface MempoolResponse
 */
export interface MempoolResponse {
    /**
     *
     * @type {Array<TransactionIdentifier>}
     * @memberof MempoolResponse
     */
    transaction_identifiers: Array<TransactionIdentifier>;
}

export function MempoolResponseFromJSON(json: any): MempoolResponse {
    return MempoolResponseFromJSONTyped(json, false);
}

export function MempoolResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): MempoolResponse {
    if (json === undefined || json === null) {
        return json;
    }
    return {
        transaction_identifiers: (json['transaction_identifiers'] as Array<any>).map(TransactionIdentifierFromJSON),
    };
}

export function MempoolResponseToJSON(value?: MempoolResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        transaction_identifiers: (value.transaction_identifiers as Array<any>).map(TransactionIdentifierToJSON),
    };
}
