/* tslint:disable */
/* eslint-disable */
/**
 * Rosetta
 * Build Once. Integrate Your Blockchain Everywhere.
 *
 * The version of the OpenAPI document: 1.4.10
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Allow, AllowFromJSON, AllowToJSON, Version, VersionFromJSON, VersionToJSON } from './';

/**
 * NetworkOptionsResponse contains information about the versioning of the node and the allowed operation statuses, operation types, and errors.
 * @export
 * @interface NetworkOptionsResponse
 */
export interface NetworkOptionsResponse {
    /**
     *
     * @type {Version}
     * @memberof NetworkOptionsResponse
     */
    version: Version;
    /**
     *
     * @type {Allow}
     * @memberof NetworkOptionsResponse
     */
    allow: Allow;
}

export function NetworkOptionsResponseFromJSON(json: any): NetworkOptionsResponse {
    return NetworkOptionsResponseFromJSONTyped(json, false);
}

export function NetworkOptionsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): NetworkOptionsResponse {
    if (json === undefined || json === null) {
        return json;
    }
    return {
        version: VersionFromJSON(json['version']),
        allow: AllowFromJSON(json['allow']),
    };
}

export function NetworkOptionsResponseToJSON(value?: NetworkOptionsResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        version: VersionToJSON(value.version),
        allow: AllowToJSON(value.allow),
    };
}
