/* tslint:disable */
/* eslint-disable */
/**
 * Rosetta
 * Build Once. Integrate Your Blockchain Everywhere.
 *
 * The version of the OpenAPI document: 1.4.10
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { NetworkIdentifier, NetworkIdentifierFromJSON, NetworkIdentifierToJSON } from './';

/**
 * A NetworkListResponse contains all NetworkIdentifiers that the node can serve information for.
 * @export
 * @interface NetworkListResponse
 */
export interface NetworkListResponse {
    /**
     *
     * @type {Array<NetworkIdentifier>}
     * @memberof NetworkListResponse
     */
    network_identifiers: Array<NetworkIdentifier>;
}

export function NetworkListResponseFromJSON(json: any): NetworkListResponse {
    return NetworkListResponseFromJSONTyped(json, false);
}

export function NetworkListResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): NetworkListResponse {
    if (json === undefined || json === null) {
        return json;
    }
    return {
        network_identifiers: (json['network_identifiers'] as Array<any>).map(NetworkIdentifierFromJSON),
    };
}

export function NetworkListResponseToJSON(value?: NetworkListResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        network_identifiers: (value.network_identifiers as Array<any>).map(NetworkIdentifierToJSON),
    };
}
