/* tslint:disable */
/* eslint-disable */
/**
 * Rosetta
 * Build Once. Integrate Your Blockchain Everywhere.
 *
 * The version of the OpenAPI document: 1.4.10
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists } from '../runtime';
import {
    AccountIdentifier,
    AccountIdentifierFromJSON,
    AccountIdentifierToJSON,
    Amount,
    AmountFromJSON,
    AmountToJSON,
    CoinChange,
    CoinChangeFromJSON,
    CoinChangeToJSON,
    OperationIdentifier,
    OperationIdentifierFromJSON,
    OperationIdentifierToJSON,
} from './';

/**
 * Operations contain all balance-changing information within a transaction. They are always one-sided (only affect 1 AccountIdentifier) and can succeed or fail independently from a Transaction. Operations are used both to represent on-chain data (Data API) and to construct new transactions (Construction API), creating a standard interface for reading and writing to blockchains.
 * @export
 * @interface Operation
 */
export interface Operation {
    /**
     *
     * @type {OperationIdentifier}
     * @memberof Operation
     */
    operation_identifier: OperationIdentifier;
    /**
     * Restrict referenced related_operations to identifier indices < the current operation_identifier.index. This ensures there exists a clear DAG-structure of relations. Since operations are one-sided, one could imagine relating operations in a single transfer or linking operations in a call tree.
     * @type {Array<OperationIdentifier>}
     * @memberof Operation
     */
    related_operations?: Array<OperationIdentifier>;
    /**
     * Type is the network-specific type of the operation. Ensure that any type that can be returned here is also specified in the NetworkOptionsResponse. This can be very useful to downstream consumers that parse all block data.
     * @type {string}
     * @memberof Operation
     */
    type: string;
    /**
     * Status is the network-specific status of the operation. Status is not defined on the transaction object because blockchains with smart contracts may have transactions that partially apply (some operations are successful and some are not). Blockchains with atomic transactions (all operations succeed or all operations fail) will have the same status for each operation. On-chain operations (operations retrieved in the `/block` and `/block/transaction` endpoints) MUST have a populated status field (anything on-chain must have succeeded or failed). However, operations provided during transaction construction (often times called "intent" in the documentation) MUST NOT have a populated status field (operations yet to be included on-chain have not yet succeeded or failed).
     * @type {string}
     * @memberof Operation
     */
    status?: string;
    /**
     *
     * @type {AccountIdentifier}
     * @memberof Operation
     */
    account?: AccountIdentifier;
    /**
     *
     * @type {Amount}
     * @memberof Operation
     */
    amount?: Amount;
    /**
     *
     * @type {CoinChange}
     * @memberof Operation
     */
    coin_change?: CoinChange;
    /**
     *
     * @type {object}
     * @memberof Operation
     */
    metadata?: object;
}

export function OperationFromJSON(json: any): Operation {
    return OperationFromJSONTyped(json, false);
}

export function OperationFromJSONTyped(json: any, ignoreDiscriminator: boolean): Operation {
    if (json === undefined || json === null) {
        return json;
    }
    return {
        operation_identifier: OperationIdentifierFromJSON(json['operation_identifier']),
        related_operations: !exists(json, 'related_operations')
            ? undefined
            : (json['related_operations'] as Array<any>).map(OperationIdentifierFromJSON),
        type: json['type'],
        status: !exists(json, 'status') ? undefined : json['status'],
        account: !exists(json, 'account') ? undefined : AccountIdentifierFromJSON(json['account']),
        amount: !exists(json, 'amount') ? undefined : AmountFromJSON(json['amount']),
        coin_change: !exists(json, 'coin_change') ? undefined : CoinChangeFromJSON(json['coin_change']),
        metadata: !exists(json, 'metadata') ? undefined : json['metadata'],
    };
}

export function OperationToJSON(value?: Operation | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        operation_identifier: OperationIdentifierToJSON(value.operation_identifier),
        related_operations:
            value.related_operations === undefined ? undefined : (value.related_operations as Array<any>).map(OperationIdentifierToJSON),
        type: value.type,
        status: value.status,
        account: AccountIdentifierToJSON(value.account),
        amount: AmountToJSON(value.amount),
        coin_change: CoinChangeToJSON(value.coin_change),
        metadata: value.metadata,
    };
}
