/* tslint:disable */
/* eslint-disable */
/**
 * Rosetta
 * Build Once. Integrate Your Blockchain Everywhere.
 *
 * The version of the OpenAPI document: 1.4.10
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CurveType, CurveTypeFromJSON, CurveTypeToJSON } from './';

/**
 * PublicKey contains a public key byte array for a particular CurveType encoded in hex. Note that there is no PrivateKey struct as this is NEVER the concern of an implementation.
 * @export
 * @interface PublicKey
 */
export interface PublicKey {
    /**
     * Hex-encoded public key bytes in the format specified by the CurveType.
     * @type {string}
     * @memberof PublicKey
     */
    hex_bytes: string;
    /**
     *
     * @type {CurveType}
     * @memberof PublicKey
     */
    curve_type: CurveType;
}

export function PublicKeyFromJSON(json: any): PublicKey {
    return PublicKeyFromJSONTyped(json, false);
}

export function PublicKeyFromJSONTyped(json: any, ignoreDiscriminator: boolean): PublicKey {
    if (json === undefined || json === null) {
        return json;
    }
    return {
        hex_bytes: json['hex_bytes'],
        curve_type: CurveTypeFromJSON(json['curve_type']),
    };
}

export function PublicKeyToJSON(value?: PublicKey | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        hex_bytes: value.hex_bytes,
        curve_type: CurveTypeToJSON(value.curve_type),
    };
}
