/* tslint:disable */
/* eslint-disable */
/**
 * Rosetta
 * Build Once. Integrate Your Blockchain Everywhere.
 *
 * The version of the OpenAPI document: 1.4.10
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists } from '../runtime';
/**
 * In blockchains with sharded state, the SubNetworkIdentifier is required to query some object on a specific shard. This identifier is optional for all non-sharded blockchains.
 * @export
 * @interface SubNetworkIdentifier
 */
export interface SubNetworkIdentifier {
    /**
     *
     * @type {string}
     * @memberof SubNetworkIdentifier
     */
    network: string;
    /**
     *
     * @type {object}
     * @memberof SubNetworkIdentifier
     */
    metadata?: object;
}

export function SubNetworkIdentifierFromJSON(json: any): SubNetworkIdentifier {
    return SubNetworkIdentifierFromJSONTyped(json, false);
}

export function SubNetworkIdentifierFromJSONTyped(json: any, ignoreDiscriminator: boolean): SubNetworkIdentifier {
    if (json === undefined || json === null) {
        return json;
    }
    return {
        network: json['network'],
        metadata: !exists(json, 'metadata') ? undefined : json['metadata'],
    };
}

export function SubNetworkIdentifierToJSON(value?: SubNetworkIdentifier | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        network: value.network,
        metadata: value.metadata,
    };
}
